"""update models

Revision ID: c369ed3700aa
Revises: b4fad0a2d190
Create Date: 2025-11-13 13:58:49.707233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c369ed3700aa'
down_revision: Union[str, Sequence[str], None] = 'b4fad0a2d190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('animals', 'description',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('animals', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.alter_column('animals', 'gender',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('animals', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('animals', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
